version: "3"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - internal
    depends_on:
      - mysql
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
    - internal
    volumes:
    - /path/to/mailhog_data:/mailhog_data
  nginx:
    build:
      context: ./nginx
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./Laravel/:/var/www/Laravel
      - ./logs/nginx:/var/log/nginx/
    container_name: nginx
  php:
    build:
      context: .
      dockerfile: php/dockerize
    networks:
      - internal
    volumes:
      - ./Laravel/:/var/www/Laravel
      - ./Logs/php.log:/var/log/fpm-php.www.log
    container_name: php
    expose:
      - "9000"
      
  mysql:
    container_name: db
    restart: always
    image: mysql:latest
    ports:
     - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - internal
networks:
  internal:
    driver: bridge
